Added sendLog in configuration file
TI-Planet/ShoutBot pull request #48
Opened 2021-03-01 20:27 UTC by ascpial

sendLog settings was added in the reperstory wich alow you to get login and logout messages

2021-03-01 20:39 UTC, LeGmask requested changes
Okay globaly it's pretty good but :

- [ ] Use tabs instead of spaces
- [ ] Rename settings
- [ ] move into parsor ... (maybe new one but come discuss about that on the discord)

2021-03-01 20:39 UTC, LeGmask commented on config.json
> +        "sendLogs": false,
Ooof that's spaces not tabs ...
Also I think sendLogs settings isn't well named, because we can think that's a debbug mode...

2021-03-01 20:39 UTC, LeGmask commented on src/tiplanet.py
> +				    message["content"]=f"*{username} se connecte au Chat.*"
As well this is spaces instead of tabs

2021-03-01 20:39 UTC, LeGmask commented on src/tiplanet.py
> +					    message["content"]=f"*{username} a été déconnecté (Temps écoulé).*"
Here same things as before ... spaces instead of tabs

2021-03-01 20:39 UTC, LeGmask commented on src/tiplanet.py
> +			if self.config.sendLogs:
maybe move this into the parsor because it's one command but there many commands such as /roll for example ...

2021-03-01 20:43 UTC, Hayleia requested changes
Small problem, "Logs" seems like a short for uh, logging, not logins/logouts. Not a big problem but more clarity wouldn't hurt. Like sendConnections rather than sendLogs.

But I'm still notifying that small problem because there are other changes to do anyways and these ones are 100% compulsory 😛
Do I see a mix of tabs and spaces that doesn't make sense?...

2021-03-01 21:40 UTC, ascpial commented on config.json
> +        "sendLogs": false,
Sorry for space, I'm playing to replace it.
For the name, I have choice `sendConnexion`

2021-03-01 21:40 UTC, ascpial commented on src/tiplanet.py
> +			if self.config.sendLogs:
Done.

2021-03-01 21:43 UTC, ascpial reviewed
Pushed tests into parser and removed spaces.

2021-03-02 11:12 UTC, LeGmask approved these changes
Way better but Connections istead of french one 😛

2021-03-02 11:12 UTC, LeGmask commented on config.json
> +		"sendConnexion": false,
It's french not english 😛

2021-03-02 11:14 UTC, LeGmask commented
Also in future, please use [gitmoji](https://gitmoji.dev/) for commit name prefix ...

2021-03-02 11:20 UTC, ascpial commented on config.json
> +		"sendConnexion": false,
✏️  Done in commit https://github.com/TI-Planet/ShoutBot/pull/48/commits/c78ca2337ec9c41b2a8e7362959c228e5ca46496

2021-03-02 11:23 UTC, LeGmask requested changes
As I says in review comment remove useless code please :D

2021-03-02 11:23 UTC, LeGmask commented on src/parser.py
> +		if msg.startswith("/login ") and self.config.sendConnections:
Here why check if we parse message ? This useless since we doesn't send any message if it's disable ...

2021-03-02 12:57 UTC, LeGmask approved these changes
LGTM!

2021-03-02 12:58 UTC, Hayleia approved these changes
LGTM

2021-03-02 13:00 UTC, merged